name: Run Boat AI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests lhafile pandas numpy scikit-learn tqdm beautifulsoup4 lxml xgboost

      - name: Run update.py
        run: python update.py
