name: Run Boat AI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: boat_AI_app
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run download.py
        working-directory: boat_AI_app
        run: python data/download.py

      - name: Run model creation
        working-directory: boat_AI_app
        run: python models_clf/make_model_clf.py

      - name: Run update.py
        working-directory: boat_AI_app
        run: python update.py






