name: Run Boat AI Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python '3.10'
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install required Python packages
        run: |
          pip install requests
          pip install lhafile
          pip install pandas
          pip install numpy
          pip install scikit-learn
          pip install tqdm
          pip install beautifulsoup4
          pip install lxml

      - name: Run download script
        run: python boat_AI_pred/data/download.py

      - name: Run model training script
        run: python boat_AI_pred/models_clf/make_model_clf.py

      - name: Run main update script
        run: python boat_AI_pred/update.py


