name: Train and Validate Boat Models

on:
  push:
    paths:
      - 'boat_AI_pred/**.py'
      - '.github/workflows/**'
      - 'environment.yml'
  workflow_dispatch:

jobs:
  train-models:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonをセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 必要なパッケージをインストール
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn xgboost joblib requests

      - name: データをダウンロード
        run: |
          python boat_AI_pred/data/download.py

      - name: モデルを作成
        run: |
          python boat_AI_pred/models_clf/make_model_clf.py
