name: BoatRace Data Download & CSV Export

on:
  workflow_dispatch:

jobs:
  download_and_convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lhafile pandas

      - name: Run download script
        run: python download.py

      - name: Upload Result CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: boatrace-result-csv
          path: result_csv/*.csv

      - name: Upload Payout CSV artifact
        uses: actions/upload-artifact@v3
        with:
          name: boatrace-payout-csv
          path: payout_csv/*.csv
