name: Run download_and_convert script

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/download_and_convert.py'
      - '.github/workflows/download_and_convert.yml'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required Python packages
        run: |
          pip install --upgrade pip
          pip install pandas requests beautifulsoup4 tqdm

      - name: Run download_and_convert.py
        run: python scripts/download_and_convert.py

      - name: Upload df_result artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: df_result
          path: artifacts/df_result.pkl

